/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myappgradle_app_helloWorldGradle */

#ifndef _Included_com_example_myappgradle_app_helloWorldGradle
#define _Included_com_example_myappgradle_app_helloWorldGradle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myappgradle_app_helloWorldGradle
 * Method:    getMessageFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myappgradle_app_helloWorldGradle_getMessageFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myappgradle_app_helloWorldGradle
 * Method:    getIntegerFromNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_myappgradle_app_helloWorldGradle_getIntegerFromNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
